### ISSUE TITLE
Document a stable .NET 7 workflow

### ISSUE THREAD

**Issue by flibitijibibo** [FNA-XNA/FNA#446]
Despite our best efforts to get people on .NET Framework, people are using .NET 7 anyway. Since we can't force them to move to Framework (not trivially anyway) we'll need to document how to avoid all the problems that Core likes to throw our way.

This is the TODO list for making an FNA setup guide:

- [ ] Setting up Visual Studio Code
    - [ ] Linux
        - [ ] Mono
        - [ ] .NET 7
    - [ ] Windows
        - [ ] .NET 4.6.2
        - [ ] .NET 7
- [ ] Windows filesystem case sensitivity
- [ ] Adding FNADllMap to all DLLs/EXEs
- [ ] Environment Variables

We are effectively building documentation to make absolutely sure that all builds done in the .NET 7 environment are as trivial to deploy for Linux as they are with MonoKickstart. The documentation is not complete until that goal is met. It's probably going to take all three of us to get this done, but the benefits will be worth it:

- No more MonoDevelop!
- More opportunities for 5bux by having documentation to point to
- More documentation for non-FNA apps wondering why their game isn't portable

**Comment by bradJM** [comment]
I'm just picking FNA back up after not using it for a bit, so if you want a new-ish user to test the documentation I'm happy to help!

**Comment by flibitijibibo** [comment]
# Developing with FNA on Linux:

The Linux development environment for FNA is supported on all distributions with Flatpak support, including SteamOS.

## Installation

### Part 1: Visual Studio Code and .NET

You may be able to find VSCode and the C# SDKs via apps like KDE Discover, but it's easier to do with a single portable terminal command:

```
flatpak install com.visualstudio.code org.freedesktop.Sdk.Extensions.mono6 org.freedesktop.Sdk.Extensions.dotnet7
```

This installs VSCode, Mono, and .NET 7 all at once!

### Part 2: Exposing .NET to Visual Studio Code

Due to the way Flatpak sandboxes applications, Mono/.NET need to be exposed to VSCode's sandbox. Again, the multiplatform solution looks like this:

```
FLATPAK_ENABLE_SDK_EXT=mono6,dotnet6 flatpak run com.visualstudio.code
```

However, some desktops such as KDE Plasma (the Steam Deck desktop mode!), have a GUI for this! You can add this via *Settings -> Applications -> Flatpak Permission Settings -> Visual Studio Code -> Advanced Permissions -> Environment*, adding a new item:

- Name: **FLATPAK_ENABLE_SDK_EXT**
- Value: **mono6,dotnet7**

It should look something like this:

![deck_vscode_csharp](https://github.com/FNA-XNA/FNA/assets/1396814/f730d7e5-aedd-4fe5-82a8-1cee3e76ea50)

### Part 3: Visual Studio Code Extensions

You should now be able to start VSCode, either via the terminal command or via the desktop shortcut (if your desktop supported Flatpak settings). Hit Ctrl+Shift+X to go to the extensions view, then search for "C# Dev Kit". Install the kit from the marketplace and let it download all of the components. You should be able to clear the search results and see the various new installed extensions!

If you're targeting .NET 7, you're good to go - however, we still recommend targeting via Mono, which requires a couple extra steps:

1. Search for and install the "Mono Debug" extension
2. Disable the C# Dev Kit extension, leaving all other extensions alone
3. Right click the C# extension and select Extension Settings
4. Search for `useModernDotNet`, uncheck Use Modern .NET
5. Search for `useOmnisharp`, check Use Omnisharp

From here, make a new project, add FNA as a project reference, and begin work!

## Running .NET Framework projects

For those migrating from Visual Studio or MonoDevelop, you'll find that running/debugging takes a few more steps - we're lobbying to streamline this process, but if you want to get debugging ASAP, you can rip off these `launch.json` and `tasks.json` files:

launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "mono",
            "request": "launch",
            "program": "${workspaceRoot}/path/to/your/bin/Debug/Game.exe",
            "cwd": "${workspaceRoot}",
            "env": {
                "LD_LIBRARY_PATH": "${workspaceRoot}/path/to/your/fnalibs/lib64/"
            }
        },
        {
            "name": "Attach",
            "type": "mono",
            "request": "attach",
            "address": "localhost",
            "port": 55555
        }
    ]
}
```

tasks.json:
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "msbuild",
            "args": [
                // Ask msbuild to generate full paths for file names.
                "/property:GenerateFullPaths=true",
                "/t:build",
                // Do not generate summary otherwise it leads to duplicate errors in Problems panel
                "/consoleloggerparameters:NoSummary",
                "THIS_IS_YOUR_GAME.sln",
                "/p:Configuration=Debug"
            ],
            "group": "build",
            "presentation": {
                // Reveal the output only if unrecognized errors occur.
                "reveal": "silent"
            },
            // Use the standard MS compiler pattern to detect errors, warnings and infos
            "problemMatcher": "$msCompile"
        }
    ]
}
```

With these in place, you should now be able to build (*Terminal -> Run Build Task*) and run (*Run -> Start Debugging*, or F5!).

## Remote Debugging for Steam Deck

Using the above launching system, it's actually possible to attach to a Steam Deck for remote C# debugging! Currently, only .NET Framework builds are supported. The process is as follows:

1. Build a Linux version (see [our documentation](https://github.com/FNA-XNA/FNA/wiki/3:-Distributing-FNA-Games#gnulinux))
2. Set up the Steam Deck devkit and upload your game (see [Valve's documentation](https://partner.steamgames.com/doc/steamdeck/loadgames), you can ignore anything involve Proton as it's not used here!)
3. On the Deck, go to your new devkit game and click *⚙️ -> Properties*
4. Under *Shortcut -> Launch Options*, enter the following excruciatingly long text (this has been filed as a [feature request](https://steamcommunity.com/groups/steamworks/discussions/27/3880473373390660324/)):

```
MONO_BUNDLED_OPTIONS='--debugger-agent=address=0.0.0.0:55555,transport=dt_socket,server=y --debug=mdb-optimizations' %command%
```

5. Launch the game and start the debugger, enjoy!

**Comment by flibitijibibo** [comment]
I've started pushing stuff to the wiki. I've re-done Page 1 to be a broader setup guide...

https://github.com/FNA-XNA/FNA/wiki/1:-Setting-Up-FNA

... and I added Steam Deck remote debugging to the distributing/packaging page:

https://github.com/FNA-XNA/FNA/wiki/3:-Distributing-FNA-Games#steam-deck-remote-debugging

**Comment by flibitijibibo** [comment]
Did my best to get the installation guide cleaned up for both Linux and Windows - the remaining tasks are mostly for new projects: FNADllMap and creating new projects are the final tasks remaining.

**Comment by flibitijibibo** [comment]
For now I've mentioned DllMap [here](https://github.com/FNA-XNA/FNA/wiki/1:-Setting-Up-FNA#net-core-fixes), though if there are any further steps needed to add support for each project we will need to document it ASAP.

The wiki went through a _ton_ of refactoring but it should now include everything needed to make a modern .NET development environment work, and I was able to verify this locally.
